[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
bun = "1.2.19"
node = "22"

[build.nixpacksConfig.variables]
NODE_ENV = "production"
BUN_ENV = "production"

[deploy]
startCommand = "bunx serve dist --single --listen 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/"
interval = "30s"
timeout = "10s"
retries = 3 

[phases.setup]
nixPkgs = ["bun", "nodejs_22"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bunx serve dist --single --listen 0.0.0.0:$PORT"
